version: '3.5'

services:
  api1: 
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    networks:
      - my-networks
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:8000
    expose: 
     - "8000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.12GB'

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    networks:
      - my-networks
    env_file: .env
    depends_on:
      - db
    ports:
      - 8001:8000
    expose: 
      - "8001"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.12GB'

  nginx: 
    image: nginx:latest
    networks:
      - my-networks
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.12'
          memory: '0.25GB'

  db: 
   image: postgres
   networks:
    - my-networks
   ports:
    - 5432:5432
   command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=2GB"
   environment:
    POSTGRES_PASSWORD: example
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '2GB'


  cache:
   image: docker.dragonflydb.io/dragonflydb/dragonfly
   networks:
    - my-networks
   ports:
    - 6379:6379
   deploy:
      resources:
        limits:
          cpus: '0.12'
          memory: '0.5GB'

networks:
  my-networks:
    driver: bridge